version: "3"
services:
  server:
    # image: toshiaki0910/jupyter_env:0.2${VIM--no-vim} 
    container_name: django_env

    build:
        context: .
        dockerfile: ./Dockerfile

    ports:
      - "8000:8000"

    environment:
        - PYTHONUNBUFFERED=1

    volumes:
      - .:/workdir

    command: python3 manage.py runserver 0.0.0.0:8000
    #stdin_open: true
    #tty: true

